Store/C2.WebApp.Store/Areas/Admin/Controllers/ContentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using C2.WebApp.Models;
using C2.WebApp.Store.Models;
using C2.DataMapping;
using C2.DataManager;
using C2.AppController;
using C2.DataModel;

namespace C2.WebApp.Store.Areas.Admin.Controllers
{
    [Authorize(Roles="Admin")]
    public class ContentController : Controller
    {

        public ContentController()
        {
            _dataContext = new AppContext("DefaultConnection");
            _dataManager = new AppDataManager(_dataContext);
        }

        AppContext _dataContext;
        AppDataManager _dataManager;

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _dataContext.Dispose();
            }

            base.Dispose(disposing);
        }

        //
        // GET: /Admin/Content/
        public ActionResult Index()
        {
            ViewBag.Supplier = SupplierModel.Current.Subject.CurrentLocalization.FullName;
            return View(new ContentPageModel
            {
                AllPagesContent = _dataManager.GetContentPages().Where(c => c.ContentType != "text/html-email").ToList()
            });
        }

        // GET: /Admin/Content/
        public ActionResult CreateEdit(long? id)
        {
            PageContent page = null;

            if (id.HasValue)
            {
                page = _dataManager.GetContentPages().FirstOrDefault(p => p.Id == id.Value);
            }
            else
            {
                page = new PageContent { ContentType = "text/html" };
            }

            return View(page);
        }

        // Post: /Admin/Content/
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult CreateEdit(PageContent model)
        {
            try
            {
                _dataManager.SaveContentPage(model);
                return RedirectToAction("Index", new { controller = model.ContentType == "text/html-email" ? "Spam" : Request.RequestContext.RouteData.Values["controller"] });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex);
            }

            return View(model);
        }
    }
}

Store/C2.WebApp.Store/Areas/Admin/Views/Content/CreateEdit.cshtml
@model C2.DataModel.PageContent
@Html.Partial("ckEditorInit", new { toolbarset = "Full" })
@Html.Partial("ckEditor", new { FCKEditor = "Text" })


@using (Html.BeginForm("CreateEdit", "Content")) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Страница</legend>
        <p>@Html.DisplayFor(m => m.Id)</p>
        
        @Html.HiddenFor(m => m.Id)
        @Html.HiddenFor(m => m.ContentType)

    <table>
        <tr>
            <td>Название</td>
            <td>@Html.TextBoxFor(m => m.Title, new { @class="text-input" })</td>
        </tr>
        <tr>
            <td>HtmlId</td>
            <td>@Html.TextBoxFor(m =>m.HtmlId, new { @class="text-input" })</td>
        </tr>
        <tr>
            <td>HtmlTitle</td>
            <td>@Html.TextBoxFor(m =>m.HtmlTitle, new { @class="text-input" })</td>
        </tr>
        <tr>
            <td>HtmlKeywords</td>
            <td>@Html.TextBoxFor(m =>m.HtmlKeywords, new { @class="text-input" })</td>
        </tr>
        <tr>
            <td>HtmlDescription</td>
            <td>@Html.TextAreaFor(m =>m.HtmlDescription, new { @class="text-input" })</td>
        </tr>
        <tr>
            <td>Текст</td>
            <td>@Html.TextArea("Text")</td>
        </tr>
    </table>
        
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    <a href="@Url.Action("Index", new { area="admin", controller=Request.RequestContext.RouteData.Values["controller"] })">Вернуться, не сохраняя</a>
</div>

@section Scripts {
}

Store/C2.WebApp.Store/Areas/Admin/Views/Content/Index.cshtml
@model C2.WebApp.Store.Models.ContentPageModel

<h2>@ViewBag.Supplier</h2>

<table>

@foreach (var page in Model.AllPagesContent)
{
    <tr>
        <td>@page.Id</td>
        <td>@page.HtmlId</td>
        <td>@page.Title</td>
        <td>@Html.ActionLink("[изм]", "CreateEdit", new { id = page.Id })</td>
    </tr>
}

</table>

@Html.ActionLink("Создать", "CreateEdit")