C2.WebApp.Store/Models/OrderViewModel.cs
using C2.DataModel.StoreModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace C2.WebApp.Store.Models
{
    public class OrderViewModel
    {
        public OrderViewParameters Parameters
        {
            get;
            set;
        }

        public List<Order> Orders
        {
            get;
            set;
        }
    }
}

C2.WebApp.Store/Areas/Admin/Controllers/OrderController.cs
using C2.AppController;
using C2.DataManager.Store;
using C2.DataMapping;
using C2.DataMapping.Store;
using C2.DataModel;
using C2.DataModel.StoreModel;
using C2.WebApp.Models;
using C2.WebApp.Store.Areas.Admin.Models;
using C2.WebApp.Store.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace C2.WebApp.Store.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class OrderController : Controller
    {
        public OrderController()
        {
            _dataContext = new StoreContext("DefaultConnection");
            _dataManager = new StoreDataManager(_dataContext);
        }

        StoreContext _dataContext;

        StoreDataManager _dataManager;

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _dataContext.Dispose();
            }

            base.Dispose(disposing);
        }

        //
        // GET: /Admin/Order/

        public ActionResult Index(OrderViewParameters parameters)
        {
            parameters.Status = OrderStatus.Created;

            OrderViewModel outModel = new OrderViewModel()
            {
                Parameters = parameters,
                Orders = DoSearch(parameters)
            };

            return View(outModel);
        }

        [HttpPost]
        public ActionResult Search(OrderViewParameters parameters)
        {
            return PartialView("_OrderList", DoSearch(parameters));
        }

        public ActionResult Item(long id)
        {
            var order = _dataContext.LoadOrderDetails(id);

            if (order == null)
            {
                return RedirectToAction("Index");
            }

            return View(order);
        }

        [HttpPost]
        public ActionResult AddOfferToOrder(long orderId, long offerId)
        {
            var _order = _dataContext.LoadOrderDetails(orderId);
            if (_order != null)
            {
                var _offer = _dataContext.LoadOfferDetails(offerId);
                if (_offer != null)
                {
                    var orderItem = _order.Items.FirstOrDefault(oi => (oi.OfferId == offerId));
                    var customerInfo = _dataContext.CustomerInfos.FirstOrDefault(c => c.UserName == _order.UserProfile.UserName);
                    bool isWholesale = (customerInfo != null && customerInfo.Status == CustomerStatus.IsWholesale);
                    if (orderItem == null)
                    {
                        orderItem = new OrderItem()
                        {
                            Id = BaseContext.GetId(),
                            Order = _order,
                            Offer = _offer,
                            PriceValue = isWholesale ? _offer.PriceOpt40.GetValueOrDefault(_offer.Price) : _offer.PriceOpt20.HasValue ? _offer.Price * (1 - _offer.PriceOpt20.Value / 100) : _offer.Price,
                            Quantity = 0
                        };
                        
                        _order.Items.Add(orderItem);
                    }
                    orderItem.Quantity++;
                    if (orderItem.Quantity > _offer.AvailQuantity)
                    {
                        // Нельзя превышать запасы.
                        orderItem.Quantity = _offer.AvailQuantity;
                    }
                    _order.UpdateTotals(isWholesale: isWholesale);

                    _dataContext.SaveChanges();

                    return View("Item", _order);
                }
            }

            return RedirectToAction("Index");
        }

        public ActionResult SetQtyAsAvailable(long id)
        {
            var order = _dataContext.LoadOrderDetails(id);

            if (order == null)
            {
                return RedirectToAction("Index");
            }

            foreach (var item in order.Items)
            {
                item.Quantity = item.AdminQuantity.GetValueOrDefault();
            }

            _dataContext.SaveChanges();

            return View("Item", order);
        }

        [HttpPost]
        public ActionResult UpdateOrder(Order order)
        {
            var _order = _dataContext.LoadOrderDetails(order.Id);
            foreach (var oi in order.Items)
            {
                var _orderItem = _dataContext.OrderItems.Include(i => i.Order).FirstOrDefault(o => o.Id == oi.Id);
                if (_orderItem != null)
                {

                    if (oi.Quantity <= 0)
                    {
                        //установили в 0 - удалим
                        _dataContext.OrderItems.Remove(_orderItem);
                    }
                    else if (oi.Quantity != _orderItem.Quantity || oi.DiscountTotal != _orderItem.DiscountTotal)
                    {
                        //установили новое значение
                        var offer = _dataContext.LoadOfferDetails(_orderItem.OfferId);

                        if (offer != null)
                        {
                            _orderItem.Quantity = oi.Quantity;

                            // нельзя отгрузить в убыток
                            if (_orderItem.DiscountTotal > _orderItem.PriceValue)
                            {
                                _orderItem.DiscountTotal = _orderItem.PriceValue;
                            }
                        }
                    }

                    if (!oi.AdminQuantity.HasValue || oi.AdminQuantity < 0)
                    {
                        oi.AdminQuantity = 0;
                    }
                    
                    _orderItem.AdminQuantity = oi.AdminQuantity;
                    _orderItem.AdminComment = oi.AdminComment;
                }

            }
            
            _order.AdminComment = order.AdminComment;

            var customerInfo = _dataContext.CustomerInfos.FirstOrDefault(c => c.UserName == _order.UserProfile.UserName);
            bool isWholesale = (customerInfo != null && customerInfo.Status == CustomerStatus.IsWholesale);

            _order.UpdateTotals(isWholesale: isWholesale);
            _dataContext.SaveChanges();

            return RedirectToAction("Item", new { id = _order.Id });
        }

        /// <summary>
        /// Принять заказ без участия пользователя или на доработку менеджеру
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Created(long id)
        {
            var order = _dataContext.Orders.Find(id);

            if (order == null)
            {
                return RedirectToAction("Index");
            }

            order.OrderStatus = OrderStatus.Created;
            _dataContext.SaveChanges();

            return RedirectToAction("Item", new { id = order.Id });
        }

        /// <summary>
        /// Запрос поставщикам
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult InvoiceRequest(long id, bool isInternal = false)
        {
            var order = _dataContext.Orders.Find(id);
            if (order == null)
            {
                return RedirectToAction("Index");
            }

            _dataManager.SendOrderItemsBySuppliers(order, Properties.Settings.Default.OrderEmailFrom, isInternal ? Properties.Settings.Default.OrderBillingEmail : null);
            _dataContext.SaveChanges();

            return RedirectToAction("Item", new { id = order.Id });
        }

        /// <summary>
        /// Отправить коментарии на почту
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult SendWithComments(long id)
        {
            var order = _dataContext.LoadOrderDetails(id);
            if (order == null)
            {
                return RedirectToAction("Index");
            }

            var customerInfo = _dataContext.CustomerInfos.Where(p => p.UserName == order.CustomerId).FirstOrDefault();
            var tpl = new OrderMailTemplate("OrderComment", "OrderItemComments", order, customerInfo);

            MailQueue mailToCustomer = new MailQueue()
            {
                Body = tpl.Execute(),
                Created = DateTime.UtcNow,
                FromEmail = Properties.Settings.Default.OrderEmailFrom,
                IsBodyHtml = true,
                Subject = string.Format(Properties.Settings.Default.OrderEmailSubject, order.Id),
                ToEmail = customerInfo != null ? customerInfo.Email : order.CustomerId
            };

            MailQueue mailToManager = new MailQueue()
            {
                Body = tpl.Execute(),
                Created = DateTime.UtcNow,
                FromEmail = Properties.Settings.Default.OrderEmailFrom,
                IsBodyHtml = true,
                Subject = string.Format(Properties.Settings.Default.OrderEmailSubject, order.Id),
                ToEmail = Properties.Settings.Default.OrderBillingEmail
            };

            MailController.SendMail(mailToManager, mailToCustomer);

            return RedirectToAction("Item", new { id = order.Id });
        }

        /// <summary>
        /// Принять заявку.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Accept(long id)
        {
            var order = _dataContext.Orders.Find(id);

            if (order == null)
            {
                return RedirectToAction("Index");
            }

            order.OrderStatus = OrderStatus.Accepted;
            _dataContext.SaveChanges();

            return RedirectToAction("Item", new { id = order.Id });
        }

        /// <summary>
        /// Отклонить заявку.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>

C2.WebApp.Store/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using C2.DAL;
using C2.DAL.Entity;
using C2.DataMapping.Store;
using C2.DataModel.StoreModel;
using Newtonsoft.Json;
using C2.WebApp.Store.Models;
using C2.DataManager.Store;
using System.Globalization;
using C2.DataModel;
using C2.AppModel;

namespace C2.WebApp.Store.Controllers
{
    public class ProductController : Controller
    {
        public ProductController()
        {
            _dataContext = new StoreContext("DefaultConnection");
            _dataManager = new StoreDataManager(_dataContext);
        }

        StoreContext _dataContext;

        StoreDataManager _dataManager;

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _dataContext.Dispose();
            }

            base.Dispose(disposing);
        }


        /// <summary>
        /// Метод для изменение веса товара в списке. 
        /// TODO: перенести в админский контрол
        /// </summary>
        /// <param name="id"></param>
        /// <param name="order"></param>
        /// <param name="categoryNodeId"></param>
        /// <param name="page"></param>
        /// <param name="pageIndex"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize(Roles="Admin")]
        public ActionResult SetOrder(long id, int order, SelectProductParams @params)
        {
            var product = _dataContext.Products.Where(p => p.Id == id).FirstOrDefault();
            if (product != null)
            {
                product.Order = order;
                _dataContext.SaveChanges();
            }

            if (Request.IsAjaxRequest())
            {
                ExtendSelectParams(@params);

                var productModel = ViewData.GetPageModel();
                productModel.SelectResult = _dataManager.SelectProducts(@params);
                productModel.CategoryNodeId = @params.CategoryNodeId;
                productModel.SelectParams = @params;

                Request.RequestContext.RouteData.Values["action"] = "Index";

                return PartialView("Index", productModel);
            }

            return RedirectToAction("Item", new { id = id });
        }

        [HttpGet]
        public ActionResult Selling(SelectProductParams @params)
        {
            @params.Selling = 30;
            return Index(@params);
        }

        //
        // GET: /Product/{SEO-Name-of-Product-Group}/{categoryNodeId}/?{pageIndex=...}
        [HttpGet]
        public ActionResult Index(SelectProductParams @params)
        {
            ExtendSelectParams(@params);

            var productModel = ViewData.GetPageModel();
            var tree = _dataManager.GetProductGroupClassifier();
            var selected = tree.AllNodes.Where(n => n.NodeId == @params.CategoryNodeId).ToList();
            productModel.CategoryNodeId = @params.CategoryNodeId;

            productModel.SelectParams = @params;

            // Загрузка каталога
            productModel.Catalog = new WebApp.Models.TreeViewModel("_ProductGroupHeader",
                tree.Roots,
                null,
                selected);

            if (selected.Count() > 0)
            {
                var classifier = selected.First();
                var group = classifier.Value as ProductGroup;
                var code = group.Code;

                productModel.PageContent = new PageContent
                {
                    Title = group.CurrentLocalization.Title,
                    Text = group.CurrentLocalization.Description,
                    HtmlDescription = group.CurrentLocalization.Description,
                    HtmlTitle = group.CurrentLocalization.Title,
                    HtmlKeywords = group.CurrentLocalization.Title,
                };

                if (classifier.Parent != null)
                {
                    productModel.PageContent.Title = classifier.Parent.Caption + ". " + productModel.PageContent.Title;
                    productModel.PageContent.HtmlTitle = classifier.Parent.Caption + " " + productModel.PageContent.HtmlTitle;
                    productModel.PageContent.HtmlKeywords = classifier.Parent.Caption + ", " + productModel.PageContent.HtmlKeywords;
                }

                productModel.AddPageContent = _dataContext.PageContents.Where(p => p.HtmlId == code).FirstOrDefault();
                if (productModel.AddPageContent != null)
                {
                    productModel.PageContent.Title += " " + productModel.AddPageContent.Title;
                    productModel.PageContent.HtmlTitle += " " + productModel.AddPageContent.HtmlTitle;
                    productModel.PageContent.HtmlKeywords += ", " + productModel.PageContent.HtmlKeywords;
                }
            }
            else
            {
                var action = RouteData.Values["action"].ToString().ToLower();
                productModel.PageContent = _dataContext.PageContents.Where(p => p.HtmlId == action).FirstOrDefault();
            }

            productModel.SelectResult = _dataManager.SelectProducts(@params);

            return View("Index", productModel);
        }

        //
        // POST: /Product/Search

        [HttpPost]
        public ActionResult Search(SelectProductParams @params)
        {
            ExtendSelectParams(@params);

            return PartialView("~/Views/Product/ProductCollection.cshtml", _dataManager.SelectProducts(@params));
        }

        //
        // GET: /Product/Item/SEO-Name-of-Product/{id}
        public ActionResult Item(long id)
        {
            if (id < 0)
            {
                //По большей части для тестирования обработки ошибок на сайте
                throw new ArgumentException();
            }

            Product product, next, prev;
            ICollection<ClassifierNode> selectedNodes;
            if (_dataManager.TryFindProduct(id, out product, out selectedNodes, out next, out prev))
            {
                var productModel = ViewData.GetPageModel();
                
                var tree = _dataManager.GetProductGroupClassifier();
                productModel.Catalog = new WebApp.Models.TreeViewModel("_ProductGroupHeader",
                            tree.Roots,
                            null,
                            tree.AllNodes.Where(n => selectedNodes.Any(sn => sn.Id == n.NodeId)).ToList());

                var model = new ProductItemViewModel
                {
                    Product = product,
                    Next = next,
                    Previous = prev
                };

                return View(model);
            }
            else
            {
                throw new HttpException(404, string.Format("Продукт {0} не найден", id));
            }
        }

        void ExtendSelectParams(SelectProductParams @params)
        {
            @params.CurrencyCode = Properties.Settings.Default.DefaultCurrencyCode;
            @params.DefaultCultureCode = Properties.Settings.Default.DefaultCultureCode;
            @params.UserCultureCode = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
        }
    }
}

C2.WebApp.Store/Views/Shared/Basket.cshtml
@model C2.DataModel.StoreModel.Order

В корзине:

<table>
@foreach (var item in Model.Items)
{
    <tr>
        <td>@item.Offer.Product.CurrentLocalization.Title</td>
        <td>@item.Quantity</td>
        <td>@item.Offer.Unit.CurrentLocalization.Title</td>
        <td>@item.Total</td>
        <td></td>
    </tr>
}
</table>

<div class="total">
Итого: @Model.Total
</div>

@if (!Model.IsEmpty())
{
    <div class="create">Оформить заказ</div>
}

C2.WebApp.Store/Views/Shared/BasketInfo.cshtml
@model C2.DataModel.StoreModel.Order

@{
    int quantity = (int)Model.Items.Sum(i => i.Quantity);
}

<div class="cart">
	<b class="l"></b><b class="r"></b><i class="@string.Format("{0}", ((Model != null) && (quantity > 0)) ? (quantity == 1 ? "few" : "many") : "")"></i>
@if (Model == null || Model.Items.Count == 0)
    {
        <text>Корзина пуста.</text>
    }
    else
    {
	    <p id="basket-text">@Html.Raw(string.Format("В вашей <a href='{2}'>корзине</a> {0} товар{3} на сумму {1:C}", quantity, Model.Total, Url.Action("Index", "Basket"), quantity >= 5 ? "ов" : quantity > 1 ? "а" : ""))
            @Html.ActionLink("Оформить заказ", "Index", "Basket")
	    </p>
    }
</div>

C2.WebApp.Store/Views/Shared/_CustomerInfo.cshtml
@model C2.DataModel.StoreModel.CustomerInfo
<div id="update-panel">
<div class="col-title">@Html.LabelFor(m => m.ContactName)</div>
<div class="col-control">@Html.EditorFor(m => m.ContactName)</div>
<div class="row-split"></div>

<div class="col-title">@Html.LabelFor(m => m.Email)</div>
<div class="col-control">@Html.EditorFor(m => m.Email)</div>
<div class="row-split"></div>

<div class="col-title">@Html.LabelFor(m => m.Phone)</div>
<div class="col-control">@Html.EditorFor(m => m.Phone)</div>
<div class="row-split"></div>

<div class="col-title">@Html.LabelFor(m => m.Organization)</div>
<div class="col-control">
    @Html.EditorFor(m => m.Organization)
    <div><em>полное название в соответствии с учредительными документами. Включает в себя организационно-правовую форму и название юридического лица или ИП без использования аббревиатур. Используется при формировании счетов на оплату.</em></div>
</div>
<div class="row-split"></div>

<div class="col-title">@Html.LabelFor(m => m.INN)</div>
<div class="col-control">@Html.EditorFor(m => m.INN)</div>
<div class="row-split"></div>

<div class="col-title">@Html.LabelFor(m => m.OGRN)</div>
<div class="col-control">@Html.EditorFor(m => m.OGRN)
    <div><em>Для организаций ОГРН, для ИП - ОГРНИП</em></div>
</div>
<div class="row-split"></div>

<div class="col-title">@Html.LabelFor(m => m.KPP)</div>
<div class="col-control">
    @Html.EditorFor(m => m.KPP)
    <div><em>Обязательно для организаций</em></div>
</div>
<div class="row-split"></div>

<div class="col-title">@Html.LabelFor(m => m.Requisites)</div>
<div class="col-control">@Html.EditorFor(m => m.Requisites)</div>
<div class="row-split"></div>

<h3>Адрес доставки</h3>

<div class="col-title">@Html.LabelFor(m => m.DeliveryAddress.PostCode)</div>
<div class="col-control">@Html.EditorFor(m => m.DeliveryAddress.PostCode) @Html.ValidationMessageFor(m => m.DeliveryAddress.PostCode)</div>
<div class="row-split"></div>

<div class="col-title">@Html.LabelFor(m => m.DeliveryAddress.Country)</div>
<div class="col-control">@Html.EditorFor(m => m.DeliveryAddress.Country)</div>
<div class="row-split"></div>

<div class="col-title">@Html.LabelFor(m => m.DeliveryAddress.Region)</div>
<div class="col-control">@Html.EditorFor(m => m.DeliveryAddress.Region)</div>
<div class="row-split"></div>

<div class="col-title">@Html.LabelFor(m => m.DeliveryAddress.City)</div>
<div class="col-control">@Html.EditorFor(m => m.DeliveryAddress.City)</div>
<div class="row-split"></div>

<div class="col-title">@Html.LabelFor(m => m.DeliveryAddress.Street)</div>
<div class="col-control">@Html.EditorFor(m => m.DeliveryAddress.Street)</div>
<div class="row-split"></div>

<div class="col-title">@Html.LabelFor(m => m.DeliveryAddress.Building)</div>
<div class="col-control">@Html.EditorFor(m => m.DeliveryAddress.Building)</div>
<div class="row-split"></div>

<div class="col-title">@Html.LabelFor(m => m.DeliveryAddress.Room)</div>
<div class="col-control">@Html.EditorFor(m => m.DeliveryAddress.Room)</div>
<div class="row-split"></div>

<div class="col-title">@Html.LabelFor(m => m.DeliveryAddress.Special)</div>
<div class="col-control">@Html.EditorFor(m => m.DeliveryAddress.Special)</div>
<div class="row-split"></div>

<div class="col-title">@Html.LabelFor(m => m.DeliveryAddress.Notes)</div>
<div class="col-control">@Html.EditorFor(m => m.DeliveryAddress.Notes)</div>
<div class="row-split"></div>
</div>

C2.WebApp.Store/Views/Shared/_Footer.cshtml
<div id="footer">

<div class="wrapper">
    <div class="article-wide">
        <div class="item dev">
            <div class="inner">
                @Html.Raw(C2.AppController.SupplierModel.Current.LeftFooterBlock)
            </div>
        </div>
        <div class="item shops">
            <div class="inner">
            <h4 class="header"><span>Клиентам</span><b></b></h4>
            <ul>
                @Html.Raw(C2.AppController.SupplierModel.Current.FirstFooterBlock)
            </ul>			
            </div>
        </div>

        <div class="item f-menu">
            <div class="inner">
            <ul>@Html.Raw(C2.AppController.SupplierModel.Current.SecondFooterBlock)</ul>

            <ul class="f-menu-r">		
                @Html.Raw(C2.AppController.SupplierModel.Current.ThirdFooterBlock)
            </ul>

            <div class="spacer"></div>
            <p class="copy">&copy; @DateTime.Now.Year - @Html.ActionLink(@C2.AppController.SupplierModel.Current.Subject.CurrentLocalization.ShortName, "Index", "Home")</p>
            </div>
        </div>
    </div>
</div>
</div>

C2.WebApp.Store/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/themes/base/css", "~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @*@Html.Partial("_LoginPartial")*@
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        @Html.Partial("_Footer")

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

C2.WebApp.Store/Views/Shared/_Order.cshtml
@model C2.DataModel.StoreModel.Order

@{
    decimal qty = 0;
    decimal admqty = 0;
    decimal admtotal = 0;
}

<div class="col-title">@Html.LabelFor(m => m.CustomerId)</div>
<div class="col-control">@Model.CustomerId</div>
<div class="clear-fix"></div>

@if (Model.UserProfile != null) {
    <div class="col-title">@Html.LabelFor(m => m.UserProfile)</div>
    <div class="col-control">@Model.UserProfile.FirstName @Model.UserProfile.LastName, @Model.UserProfile.Phone</div>
    <div class="clear-fix"></div>
}

@if(Model.Delivery != null) {
<div class="col-title">@Html.LabelFor(m => m.Delivery)</div>
<div class="col-control">@Html.Raw(Model.Delivery.Replace("\n", "<br/>"))</div>
<div class="clear-fix"></div>
}

<div class="col-title">@Html.LabelFor(m => m.UserComment)</div>
<div class="col-control">@Html.TextAreaFor(m => m.UserComment, new { @readonly=true })</div>
<div class="clear-fix"></div>

<div class="col-title">@Html.LabelFor(m => m.OrderStatus)</div>
<div class="col-control">@Html.Partial("_OrderStatus", @Model.OrderStatus)</div>
<div class="clear-fix"></div>

<div class="col-title">@Html.LabelFor(m => m.Total)</div>
<div class="col-control">@Model.Total.ToString("N2") р.</div>
<div class="clear-fix"></div>

<div class="col-title">@Html.LabelFor(m => m.TotalPayment)</div>
<div class="col-control">@Model.TotalPayment.ToString("N2") р.</div>
<div class="clear-fix"></div>

<div class="col-title">@Html.LabelFor(m => m.IsPreorder)</div>
<div class="col-control">@Model.IsPreorder.ToString(System.Globalization.CultureInfo.CurrentUICulture)</div>
<div class="clear-fix"></div>

<div class="table">
    <div class="table-header">
        <div>
            <div>Продукт</div>
            <div>Цена</div>
            <div>Кол-во</div>
            <div>Сумма</div>
            <div>Характеристики</div>
            @if (User.IsInRole("Admin")) {
                <div>Наличие на складе</div>
                <div>Сумма по наличию</div>
                <div>Комментарий</div>
            }
        </div>
        <div class="clear-fix"></div>
    </div>
    <div class="table-body">
        @using (Html.BeginForm("UpdateOrder", "Order")) {
            @Html.HiddenFor(m => m.Id)
            foreach (var item in Model.Items)
            {
                qty += item.Quantity;
                var avail = item.AdminQuantity.HasValue ? item.AdminQuantity.Value :
                       (item.Quantity > item.Offer.AvailQuantity) ? item.Offer.AvailQuantity : item.Quantity;
                admqty += avail;
                admtotal += avail * item.PriceValue;
            }
            
                @Html.EditorFor(m => m.Items)

            if (User.IsInRole("Admin")) {

                <div class="summary">
                    <div></div>
                    <div></div>
                    <div>@qty.ToString("#")</div>
                    <div></div>
                    <div></div>
                    <div>@admqty.ToString("#")</div>
                    <div>@admtotal.ToString("N2")</div>
                </div>
                <div class="clear-fix"></div>
                <div>Комментарий админа для себя</div>
                <div class="col-control">@Html.TextAreaFor(m => m.AdminComment)</div>
                <div class="clear-fix"></div>
                <input type="submit" value="Сохранить заказ" />
            }
        }
    </div>
</div>

C2.WebApp.Store/Views/Shared/_OrderStatus.cshtml
@using C2.DataModel.StoreModel

@model OrderStatus

@Model.ToDescription()

C2.WebApp.Store/Views/Shared/_ProductGroupHeader.cshtml
@using C2.Globalization.Transliteration
@using C2.AppModel
@using C2.DataModel.StoreModel
@model TreeNodeModel

@{
    var productGroup = ((ProductGroup)Model.Value);
}
@Html.ActionLink(productGroup.CurrentLocalization.Title, "Index", "Product", new { categorySeoName = productGroup.CurrentLocalization.Title.UnidecodeStrong(), categoryNodeId = Model.NodeId }, null)